// Checkout combinations data extracted from CSV
const checkoutData = {
  170: {
    dartsRequired: 3,
    primary: 'T20-T20-Bull',
    alternatives: [],
    notes: 'Maximum finish',
  },
  169: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  168: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  167: {
    dartsRequired: 3,
    primary: 'T20-T19-Bull',
    alternatives: [],
    notes: '',
  },
  166: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  165: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  164: {
    dartsRequired: 3,
    primary: 'T20-T18-Bull',
    alternatives: ['T19-T19-Bull'],
    notes: '',
  },
  163: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  162: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  161: {
    dartsRequired: 3,
    primary: 'T20-T17-Bull',
    alternatives: [],
    notes: '',
  },
  160: {
    dartsRequired: 3,
    primary: 'T20-T20-D20',
    alternatives: [],
    notes: '',
  },
  159: { dartsRequired: 0, primary: 'IMPOSSIBLE', alternatives: [], notes: '' },
  158: {
    dartsRequired: 3,
    primary: 'T20-T20-D19',
    alternatives: [],
    notes: '',
  },
  157: {
    dartsRequired: 3,
    primary: 'T20-T19-D20',
    alternatives: [],
    notes: '',
  },
  156: {
    dartsRequired: 3,
    primary: 'T20-T20-D18',
    alternatives: [],
    notes: '',
  },
  155: {
    dartsRequired: 3,
    primary: 'T20-T19-D19',
    alternatives: [],
    notes: '',
  },
  154: {
    dartsRequired: 3,
    primary: 'T20-T18-D20',
    alternatives: ['T19-T19-D19'],
    notes: '',
  },
  153: {
    dartsRequired: 3,
    primary: 'T20-T19-D18',
    alternatives: [],
    notes: '',
  },
  152: {
    dartsRequired: 3,
    primary: 'T20-T20-D16',
    alternatives: [],
    notes: '',
  },
  151: {
    dartsRequired: 3,
    primary: 'T20-T17-D20',
    alternatives: [],
    notes: '',
  },
  150: {
    dartsRequired: 3,
    primary: 'T20-T18-D18',
    alternatives: [],
    notes: '',
  },
  149: {
    dartsRequired: 3,
    primary: 'T20-T19-D16',
    alternatives: [],
    notes: '',
  },
  148: {
    dartsRequired: 3,
    primary: 'T20-T20-D14',
    alternatives: [],
    notes: '',
  },
  147: {
    dartsRequired: 3,
    primary: 'T20-T17-D18',
    alternatives: [],
    notes: '',
  },
  146: {
    dartsRequired: 3,
    primary: 'T20-T18-D16',
    alternatives: [],
    notes: '',
  },
  145: {
    dartsRequired: 3,
    primary: 'T20-T19-D14',
    alternatives: [],
    notes: '',
  },
  144: {
    dartsRequired: 3,
    primary: 'T20-T20-D12',
    alternatives: [],
    notes: '',
  },
  143: {
    dartsRequired: 3,
    primary: 'T20-T17-D16',
    alternatives: [],
    notes: '',
  },
  142: {
    dartsRequired: 3,
    primary: 'T20-T14-D20',
    alternatives: ['T19-T19-D14'],
    notes: '',
  },
  141: {
    dartsRequired: 3,
    primary: 'T20-T19-D12',
    alternatives: [],
    notes: '',
  },
  140: {
    dartsRequired: 3,
    primary: 'T20-T20-D10',
    alternatives: [],
    notes: '',
  },
  139: {
    dartsRequired: 3,
    primary: 'T20-T13-D20',
    alternatives: ['T19-T18-D14'],
    notes: '',
  },
  138: {
    dartsRequired: 3,
    primary: 'T20-T18-D12',
    alternatives: [],
    notes: '',
  },
  137: {
    dartsRequired: 3,
    primary: 'T20-T19-D10',
    alternatives: [],
    notes: '',
  },
  136: { dartsRequired: 3, primary: 'T20-T20-D8', alternatives: [], notes: '' },
  135: {
    dartsRequired: 3,
    primary: 'T20-T17-D12',
    alternatives: [],
    notes: '',
  },
  134: {
    dartsRequired: 3,
    primary: 'T20-T14-D16',
    alternatives: [],
    notes: '',
  },
  133: { dartsRequired: 3, primary: 'T20-T19-D8', alternatives: [], notes: '' },
  132: {
    dartsRequired: 3,
    primary: 'T20-T20-D6',
    alternatives: ['T19-T19-D9'],
    notes: '',
  },
  131: {
    dartsRequired: 3,
    primary: 'T20-T13-D16',
    alternatives: [],
    notes: '',
  },
  130: { dartsRequired: 3, primary: 'T20-T18-D8', alternatives: [], notes: '' },
  129: {
    dartsRequired: 3,
    primary: 'T19-T16-D12',
    alternatives: [],
    notes: '',
  },
  128: {
    dartsRequired: 3,
    primary: 'T18-T14-D16',
    alternatives: [],
    notes: '',
  },
  127: { dartsRequired: 3, primary: 'T20-T17-D8', alternatives: [], notes: '' },
  126: { dartsRequired: 3, primary: 'T19-T19-D6', alternatives: [], notes: '' },
  125: {
    dartsRequired: 3,
    primary: 'T18-T19-D8',
    alternatives: ['T20-T15-D10'],
    notes: '',
  },
  124: { dartsRequired: 3, primary: 'T20-T20-D2', alternatives: [], notes: '' },
  123: { dartsRequired: 3, primary: 'T19-T16-D9', alternatives: [], notes: '' },
  122: { dartsRequired: 3, primary: 'T18-T20-D4', alternatives: [], notes: '' },
  121: { dartsRequired: 3, primary: 'T17-T20-D5', alternatives: [], notes: '' },
  120: {
    dartsRequired: 3,
    primary: 'T20-S20-D20',
    alternatives: [],
    notes: '',
  },
  119: {
    dartsRequired: 3,
    primary: 'T19-T20-D1',
    alternatives: ['T20-S19-D20'],
    notes: '',
  },
  118: {
    dartsRequired: 3,
    primary: 'T20-S18-D20',
    alternatives: [],
    notes: '',
  },
  117: {
    dartsRequired: 3,
    primary: 'T20-S17-D20',
    alternatives: [],
    notes: '',
  },
  116: {
    dartsRequired: 3,
    primary: 'T20-S16-D20',
    alternatives: [],
    notes: '',
  },
  115: {
    dartsRequired: 3,
    primary: 'T20-S15-D20',
    alternatives: [],
    notes: '',
  },
  114: {
    dartsRequired: 3,
    primary: 'T20-S14-D20',
    alternatives: [],
    notes: '',
  },
  113: {
    dartsRequired: 3,
    primary: 'T20-S13-D20',
    alternatives: [],
    notes: '',
  },
  112: {
    dartsRequired: 3,
    primary: 'T20-S12-D20',
    alternatives: [],
    notes: '',
  },
  111: {
    dartsRequired: 3,
    primary: 'T20-S11-D20',
    alternatives: [],
    notes: '',
  },
  110: {
    dartsRequired: 3,
    primary: 'T20-S10-D20',
    alternatives: [],
    notes: '',
  },
  109: { dartsRequired: 3, primary: 'T20-S9-D20', alternatives: [], notes: '' },
  108: { dartsRequired: 3, primary: 'T20-S8-D20', alternatives: [], notes: '' },
  107: { dartsRequired: 3, primary: 'T20-S7-D20', alternatives: [], notes: '' },
  106: { dartsRequired: 3, primary: 'T20-S6-D20', alternatives: [], notes: '' },
  105: { dartsRequired: 3, primary: 'T20-S5-D20', alternatives: [], notes: '' },
  104: { dartsRequired: 3, primary: 'T20-S4-D20', alternatives: [], notes: '' },
  103: { dartsRequired: 3, primary: 'T20-S3-D20', alternatives: [], notes: '' },
  102: { dartsRequired: 3, primary: 'T20-S2-D20', alternatives: [], notes: '' },
  101: { dartsRequired: 3, primary: 'T20-S1-D20', alternatives: [], notes: '' },
  100: { dartsRequired: 2, primary: 'T20-D20', alternatives: [], notes: '' },
  99: { dartsRequired: 2, primary: 'T19-D21', alternatives: [], notes: '' },
  98: { dartsRequired: 2, primary: 'T20-D19', alternatives: [], notes: '' },
  97: { dartsRequired: 2, primary: 'T19-D20', alternatives: [], notes: '' },
  96: { dartsRequired: 2, primary: 'T20-D18', alternatives: [], notes: '' },
  95: { dartsRequired: 2, primary: 'T19-D19', alternatives: [], notes: '' },
  94: { dartsRequired: 2, primary: 'T18-D20', alternatives: [], notes: '' },
  93: { dartsRequired: 2, primary: 'T19-D18', alternatives: [], notes: '' },
  92: { dartsRequired: 2, primary: 'T20-D16', alternatives: [], notes: '' },
  91: { dartsRequired: 2, primary: 'T17-D20', alternatives: [], notes: '' },
  90: { dartsRequired: 2, primary: 'T18-D18', alternatives: [], notes: '' },
  89: { dartsRequired: 2, primary: 'T19-D16', alternatives: [], notes: '' },
  88: { dartsRequired: 2, primary: 'T16-D20', alternatives: [], notes: '' },
  87: { dartsRequired: 2, primary: 'T17-D18', alternatives: [], notes: '' },
  86: { dartsRequired: 2, primary: 'T18-D16', alternatives: [], notes: '' },
  85: { dartsRequired: 2, primary: 'T19-D14', alternatives: [], notes: '' },
  84: { dartsRequired: 2, primary: 'T20-D12', alternatives: [], notes: '' },
  83: { dartsRequired: 2, primary: 'T17-D16', alternatives: [], notes: '' },
  82: {
    dartsRequired: 2,
    primary: 'T14-D20',
    alternatives: ['Bull-D16'],
    notes: '',
  },
  81: { dartsRequired: 2, primary: 'T19-D12', alternatives: [], notes: '' },
  80: { dartsRequired: 2, primary: 'T20-D10', alternatives: [], notes: '' },
  79: { dartsRequired: 2, primary: 'T13-D20', alternatives: [], notes: '' },
  78: { dartsRequired: 2, primary: 'T18-D12', alternatives: [], notes: '' },
  77: { dartsRequired: 2, primary: 'T19-D10', alternatives: [], notes: '' },
  76: { dartsRequired: 2, primary: 'T20-D8', alternatives: [], notes: '' },
  75: { dartsRequired: 2, primary: 'T17-D12', alternatives: [], notes: '' },
  74: { dartsRequired: 2, primary: 'T14-D16', alternatives: [], notes: '' },
  73: { dartsRequired: 2, primary: 'T19-D8', alternatives: [], notes: '' },
  72: { dartsRequired: 2, primary: 'T16-D12', alternatives: [], notes: '' },
  71: { dartsRequired: 2, primary: 'T13-D16', alternatives: [], notes: '' },
  70: { dartsRequired: 2, primary: 'T18-D8', alternatives: [], notes: '' },
  69: { dartsRequired: 2, primary: 'T15-D12', alternatives: [], notes: '' },
  68: { dartsRequired: 2, primary: 'T20-D4', alternatives: [], notes: '' },
  67: { dartsRequired: 2, primary: 'T17-D8', alternatives: [], notes: '' },
  66: { dartsRequired: 2, primary: 'T14-D12', alternatives: [], notes: '' },
  65: { dartsRequired: 2, primary: 'T19-D4', alternatives: [], notes: '' },
  64: { dartsRequired: 2, primary: 'T16-D8', alternatives: [], notes: '' },
  63: { dartsRequired: 2, primary: 'T13-D12', alternatives: [], notes: '' },
  62: { dartsRequired: 2, primary: 'T18-D4', alternatives: [], notes: '' },
  61: { dartsRequired: 2, primary: 'T15-D8', alternatives: [], notes: '' },
  60: { dartsRequired: 2, primary: 'S20-D20', alternatives: [], notes: '' },
  59: { dartsRequired: 2, primary: 'S19-D20', alternatives: [], notes: '' },
  58: { dartsRequired: 2, primary: 'S18-D20', alternatives: [], notes: '' },
  57: { dartsRequired: 2, primary: 'S17-D20', alternatives: [], notes: '' },
  56: { dartsRequired: 2, primary: 'S16-D20', alternatives: [], notes: '' },
  55: { dartsRequired: 2, primary: 'S15-D20', alternatives: [], notes: '' },
  54: { dartsRequired: 2, primary: 'S14-D20', alternatives: [], notes: '' },
  53: { dartsRequired: 2, primary: 'S13-D20', alternatives: [], notes: '' },
  52: { dartsRequired: 2, primary: 'S12-D20', alternatives: [], notes: '' },
  51: { dartsRequired: 2, primary: 'S11-D20', alternatives: [], notes: '' },
  50: {
    dartsRequired: 1,
    primary: 'Bull',
    alternatives: ['S10-D20'],
    notes: '',
  },
  49: { dartsRequired: 2, primary: 'S9-D20', alternatives: [], notes: '' },
  48: { dartsRequired: 2, primary: 'S8-D20', alternatives: [], notes: '' },
  47: { dartsRequired: 2, primary: 'S7-D20', alternatives: [], notes: '' },
  46: { dartsRequired: 2, primary: 'S6-D20', alternatives: [], notes: '' },
  45: { dartsRequired: 2, primary: 'S5-D20', alternatives: [], notes: '' },
  44: { dartsRequired: 2, primary: 'S4-D20', alternatives: [], notes: '' },
  43: { dartsRequired: 2, primary: 'S3-D20', alternatives: [], notes: '' },
  42: { dartsRequired: 2, primary: 'S2-D20', alternatives: [], notes: '' },
  41: { dartsRequired: 2, primary: 'S1-D20', alternatives: [], notes: '' },
  40: { dartsRequired: 1, primary: 'D20', alternatives: [], notes: '' },
  39: { dartsRequired: 2, primary: 'S7-D16', alternatives: [], notes: '' },
  38: { dartsRequired: 1, primary: 'D19', alternatives: [], notes: '' },
  37: { dartsRequired: 2, primary: 'S5-D16', alternatives: [], notes: '' },
  36: { dartsRequired: 1, primary: 'D18', alternatives: [], notes: '' },
  35: { dartsRequired: 2, primary: 'S3-D16', alternatives: [], notes: '' },
  34: { dartsRequired: 1, primary: 'D17', alternatives: [], notes: '' },
  33: { dartsRequired: 2, primary: 'S1-D16', alternatives: [], notes: '' },
  32: { dartsRequired: 1, primary: 'D16', alternatives: [], notes: '' },
  31: { dartsRequired: 2, primary: 'S7-D12', alternatives: [], notes: '' },
  30: { dartsRequired: 1, primary: 'D15', alternatives: [], notes: '' },
  29: { dartsRequired: 2, primary: 'S5-D12', alternatives: [], notes: '' },
  28: { dartsRequired: 1, primary: 'D14', alternatives: [], notes: '' },
  27: { dartsRequired: 2, primary: 'S3-D12', alternatives: [], notes: '' },
  26: { dartsRequired: 1, primary: 'D13', alternatives: [], notes: '' },
  25: { dartsRequired: 2, primary: 'S1-D12', alternatives: [], notes: '' },
  24: { dartsRequired: 1, primary: 'D12', alternatives: [], notes: '' },
  23: { dartsRequired: 2, primary: 'S7-D8', alternatives: [], notes: '' },
  22: { dartsRequired: 1, primary: 'D11', alternatives: [], notes: '' },
  21: { dartsRequired: 2, primary: 'S5-D8', alternatives: [], notes: '' },
  20: { dartsRequired: 1, primary: 'D10', alternatives: [], notes: '' },
  19: { dartsRequired: 2, primary: 'S3-D8', alternatives: [], notes: '' },
  18: { dartsRequired: 1, primary: 'D9', alternatives: [], notes: '' },
  17: { dartsRequired: 2, primary: 'S1-D8', alternatives: [], notes: '' },
  16: { dartsRequired: 1, primary: 'D8', alternatives: [], notes: '' },
  15: { dartsRequired: 2, primary: 'S7-D4', alternatives: [], notes: '' },
  14: { dartsRequired: 1, primary: 'D7', alternatives: [], notes: '' },
  13: { dartsRequired: 2, primary: 'S5-D4', alternatives: [], notes: '' },
  12: { dartsRequired: 1, primary: 'D6', alternatives: [], notes: '' },
  11: { dartsRequired: 2, primary: 'S3-D4', alternatives: [], notes: '' },
  10: { dartsRequired: 1, primary: 'D5', alternatives: [], notes: '' },
  9: { dartsRequired: 2, primary: 'S1-D4', alternatives: [], notes: '' },
  8: { dartsRequired: 1, primary: 'D4', alternatives: [], notes: '' },
  7: { dartsRequired: 2, primary: 'S3-D2', alternatives: [], notes: '' },
  6: { dartsRequired: 1, primary: 'D3', alternatives: [], notes: '' },
  5: { dartsRequired: 2, primary: 'S1-D2', alternatives: [], notes: '' },
  4: { dartsRequired: 1, primary: 'D2', alternatives: [], notes: '' },
  3: { dartsRequired: 2, primary: 'S1-D1', alternatives: [], notes: '' },
  2: { dartsRequired: 1, primary: 'D1', alternatives: [], notes: '' },
};

// Get checkout information for a given score
export const getCheckoutInfo = (score) => {
  return checkoutData[score] || null;
};

// Check if a score is finishable
export const isFinishable = (score) => {
  const info = getCheckoutInfo(score);
  return info && info.dartsRequired > 0 && info.primary !== 'IMPOSSIBLE';
};

// Get the maximum score that shows checkout hints
export const getMaxCheckoutHintScore = () => {
  return 170; // Show hints for scores 170 and below
};

// Check if checkout hints should be shown for a score
export const shouldShowCheckoutHint = (score) => {
  return score <= 170 && score >= 2 && isFinishable(score);
};

// Format checkout combination for display
export const formatCheckout = (combination) => {
  if (!combination || combination === 'IMPOSSIBLE') {
    return null;
  }

  return combination
    .replace(/T(\d+)/g, '3×$1') // T20 → 3×20
    .replace(/D(\d+)/g, '2×$1') // D20 → 2×20
    .replace(/S(\d+)/g, '$1') // S20 → 20
    .replace(/Bull/g, 'Bull') // Bull stays Bull
    .replace(/-/g, ' → '); // - becomes →
};

export default checkoutData;
